site_name: 图像处理Python库
repo_url: https://github.com/SkylerHu/py-img-processor
docs_dir: .

theme:
  name: readthedocs
#  name: material
#  name: mkdocs
  language: zh

nav:
  - 首页: README.md
  - 使用(Usage): docs/Reference.md
  - Release Notes: docs/CHANGELOG-1.x.md
  - 贡献者指南: docs/CONTRIBUTING.md

plugins:
  - same-dir
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [imgprocessor]
          options:
            heading_level: 3
            show_root_heading: true
            show_symbol_type_heading: true
            show_source: false
          selection:
            docstring_style: google
